# ベースイメージとして、GolangのAlpine Linuxを使用
FROM golang:1.20.4-alpine3.17 as builder
# 作業ディレクトリを設定
WORKDIR /app
# アップデートとgitのインストール 
RUN apk update && apk add git --no-cache git curl 
RUN apk update && apk add bash

COPY . .
# 実行コマンドを設定
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w" -a -o /main ./cmd

#ビルド後アプリ実行
FROM alpine:alpine3.17
RUN apk update && apk add bash
RUN apk --no-cache add ca-certificates
COPY . .
COPY --from=builder /main ./
RUN chmod +x ./main
EXPOSE 8080
CMD ./main