version: "3.9"

services:
  #backendの設定
  chatbot-server:
    build:
      context: .
      dockerfile: ../Dockerfile.backend
    networks:
      - chatbot-network
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    restart: always
  #dbの設定
  chatbot-db:
    build:
      context: .
      dockerfile: ../Dockerfile.db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - chatbot-volume:/var/lib/mysql
    networks:
      - chatbot-network
networks:
  chatbot-network:

volumes:
  chatbot-volume: